const mongoose = require("mongoose");

// =============================
// Question Schema
// =============================
const questionSchema = new mongoose.Schema({
    question: {
        type: String,
        required: true,
    },

    // Correct Answer generated by Gemini
    answer: {
        type: String,
        required: true,
    },

    // User's Submitted Answer
    userAnswer: {
        type: String,
        default: "",
    },

    // AI Score (0-10)
    score: {
        type: Number,
        default: 0,
    },

    // AI Feedback
    feedback: {
        type: String,
        default: "",
    },
});

// =============================
// Interview Schema
// =============================
const interviewSchema = new mongoose.Schema(
    {
        // User
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },

        // Job Role
        role: {
            type: String,
            required: true,
        },

        // Experience
        experience: {
            type: String,
            required: true,
        },

        // Tech Stack
        techStack: [
            {
                type: String,
            },
        ],

        // Difficulty
        difficulty: {
            type: String,
            enum: ["Easy", "Medium", "Hard"],
            default: "Medium",
        },

        // Number of Questions
        numberOfQuestions: {
            type: Number,
            default: 10,
        },

        // Questions Array
        questions: [questionSchema],

        // Overall Interview Score
        score: {
            type: Number,
            default: 0,
        },

        // Overall AI Feedback
        feedback: {
            type: String,
            default: "",
        },

        // Interview Status
        status: {
            type: String,
            enum: ["Pending", "Completed"],
            default: "Pending",
        },
    },
    {
        timestamps: true,
    }
);

module.exports = mongoose.model("Interview", interviewSchema);